In [12]:
##### import numpy as np

# Input matrices
A = np.array([list(map(float, input("Enter row elements of A: ").split())) for _ in range(int(input("Rows of A: ")))])
B = np.array([list(map(float, input("Enter row elements of B: ").split())) for _ in range(int(input("Rows of B: ")))])

# Operations
C = np.dot(A, B) if A.shape[1] == B.shape[0] else None
D = A + B if A.shape == B.shape else None

# Results
print("\nC =\n", C)
print("D =\n", D)

if C is not None and C.shape[0] == C.shape[1]:
    print("Determinant of C:", np.linalg.det(C))
if D is not None and D.shape[0] == D.shape[1]:
    print("Determinant of D:", np.linalg.det(D))

if C is not None: print("Transpose of C:\n", C.T)
if D is not None: print("Transpose of D:\n", D.T)


Rows of A:  2
Enter row elements of A:  2 3
Enter row elements of A:  1 2
Rows of B:  2
Enter row elements of B:  1 3
Enter row elements of B:  2 3



C =
 [[ 8. 15.]
 [ 5.  9.]]
D =
 [[3. 6.]
 [3. 5.]]
Determinant of C: -2.9999999999999996
Determinant of D: -3.0000000000000004
Transpose of C:
 [[ 8.  5.]
 [15.  9.]]
Transpose of D:
 [[3. 3.]
 [6. 5.]]


In [13]:
import numpy as np

# Input matrices
A = np.array([list(map(float, input("Enter row of A: ").split())) for _ in range(int(input("Rows of A: ")))])
B = np.array([list(map(float, input("Enter row of B: ").split())) for _ in range(int(input("Rows of B: ")))])

# a. Dot product
C = np.dot(A, B) if A.shape[1] == B.shape[0] else None
print("\nC =\n", C)

# b. Eigenvectors
eigvecs_A = np.linalg.eig(A)[1]
eigvecs_B = np.linalg.eig(B)[1]
print("\nEigenvectors of A:\n", eigvecs_A)
print("\nEigenvectors of B:\n", eigvecs_B)

# c. Addition of eigenvectors
if eigvecs_A.shape == eigvecs_B.shape:
    print("\nAddition of eigenvectors:\n", eigvecs_A + eigvecs_B)
else:
    print("\nCannot add eigenvectors (shape mismatch)")

# d. Diagonal matrix of C
if C is not None and C.shape[0] == C.shape[1]:
    print("\nDiagonal matrix of C:\n", np.diag(np.diag(C)))


Rows of A:  2
Enter row of A:  3 2
Enter row of A:  1 2
Rows of B:  2
Enter row of B:  4 1
Enter row of B:  3 4



C =
 [[18. 11.]
 [10.  9.]]

Eigenvectors of A:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]

Eigenvectors of B:
 [[ 0.5       -0.5      ]
 [ 0.8660254  0.8660254]]

Addition of eigenvectors:
 [[ 1.39442719 -1.20710678]
 [ 1.313239    1.57313218]]

Diagonal matrix of C:
 [[18.  0.]
 [ 0.  9.]]
